public enum ClientConnectionState {

    UNSECURE,

    CONNECTION_PROTOCOL_STEP_1,
    CONNECTION_PROTOCOL_STEP_2,
    CONNECTION_PROTOCOL_STEP_3,

    SECURE_CHAT_PROTOCOL_STEP_1,
    SECURE_CHAT_PROTOCOL_STEP_2,
    SSL_HANDSHAKE_START,
    SSL_HANDSHAKE,
    SESSION_KEY,
    SESSION_KEY_RENEW

}
